repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: '5e374fd'
    hooks:
        - id: prettier
          types_or: [css, javascript, jsx, ts, tsx, html, json]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--color", "--line-length", "119"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude : ^api/moderation/tests/|^api/moderation/views.py|^api/moderation/migrations/|^api/moderation/models.py|^api/tests/|^api/analysis/tests/|^api/cm/django_saml2_auth/|^api/cm/tests/|^api/moderation/serializers.py
        args: ["--convention=google"]
        additional_dependencies: ["toml"]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length=119", "--extend-ignore=E203,W503"]
        exclude: ^api/cm/django_saml2_auth/
